task complite
mate-academy/js_task_parse_list_DOM pull request #341
Opened 2021-12-07 03:42 UTC by voronvasia

https://voronvasia.github.io/js_task_parse_list_DOM/

2021-12-07 15:07 UTC, varseniuk requested changes

2021-12-07 15:07 UTC, varseniuk commented on src/scripts/main.js
> +  for (const person of employeeList) {
Щоб не робити лишніх дій, можна використати метод map до employeeList:
```
return [...employeeList].map(el => ({
    name: el.innerText,
.....
```

2021-12-07 18:09 UTC, vkryvytskyy approved these changes

2021-12-07 18:09 UTC, vkryvytskyy commented on src/scripts/main.js
> +  const salary = employeeList.sort((
```suggestion
  const sortedEmployees = employeeList.sort((
```

2021-12-07 18:09 UTC, vkryvytskyy commented on src/scripts/main.js
> +  return ul;
```suggestion
  ul.append(...sortedEmployees);
```
Возвращать из функции ничего не надо

2021-12-08 08:56 UTC, varseniuk approved these changes

2023-12-09 20:06 UTC, closed without merging