Solution parse_list_DOM
mate-academy/js_task_parse_list_DOM pull request #733
Opened 2023-02-13 11:27 UTC by NazariiAlieksieiev

[DEMO LINK](https://NazariiAlieksieiev.github.io/js_task_parse_list_DOM/)

2023-02-13 16:30 UTC, mykhalenych requested changes

2023-02-13 16:30 UTC, mykhalenych commented on src/scripts/main.js
> +  const Employees = [];
bad naming
```suggestion
  const employees = [];
```

2023-02-13 16:30 UTC, mykhalenych commented on src/scripts/main.js
> +  for (let i = 0; i < list.children.length; i++) {
use array method instead of for, sort will be better

2023-02-13 16:30 UTC, mykhalenych commented on src/scripts/main.js
> +  for (let i = 0; i < sortedEmployees.length; i++) {
```suggestion
```

2023-02-13 16:30 UTC, mykhalenych commented on src/scripts/main.js
> +    list.appendChild(sortedEmployees[i]);
```suggestion
    list.append(...sortedEmployees);
```

2023-02-13 16:30 UTC, mykhalenych commented on src/scripts/main.js
> +  for (let i = 0; i < list.children.length; i++) {
use map instead

2023-02-14 11:42 UTC, IvanFesenko requested changes
Please refactor without separate variables

2023-02-14 11:42 UTC, IvanFesenko commented on src/scripts/main.js
> +  return employees;
map return new array, no need to create separate variable
```suggestion
  return [...list.children].map(employee => ({
    name: employee.textContent.trim(),
    position: employee.dataset.position,
    salary: employee.dataset.salary,
    age: employee.dataset.age,
  }));
```

2023-02-14 11:42 UTC, IvanFesenko commented on src/scripts/main.js
> +    employeeB.dataset.salary - emloyeeA.dataset.salary);
Refactor without creating separate variable. You can see example below.

2023-02-14 16:37 UTC, mykhalenych approved these changes

2024-07-27 11:17 UTC, closed without merging